language: php
php:
  - nightly
  - hhvm
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
before_script: composer -n --prefer-source install
script: vendor/bin/phpunit
after_success: vendor/bin/php-coveralls
