language: php
php:
  - hhvm
  - 7.2
  - 7.1
  - 7.0
  - 5.6
before_script: composer -n --prefer-source install --dev --no-interaction
script: vendor/bin/phpunit
after_success: vendor/bin/php-coveralls
